dpi-aware=yes
icon-theme=Papirus-Dark
#width=25
#font=Hack:weight=bold:size=36
#line-height=50
fields=name,generic,comment,categories,filename,keywords
terminal=foot -e
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=no

[colors]
background=232136cc
selection=D3C6AA
border=232136cc

[border]
radius=20

[dmenu]
exit-immediately-if-empty=yes
