dpi-aware=yes
icon-theme=Papirus-Dark
#width=25
#font=Hack:weight=bold:size=36
#line-height=50
fields=name,generic,comment,categories,filename,keywords
terminal=foot -e
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=no

[colors]
background=272E33cc
selection=A7C080ff
border=272E33cc

[border]
radius=0

[dmenu]
exit-immediately-if-empty=yes
